# Generated by Django 4.0.3 on 2022-03-15 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proudct',
            new_name='Product',
        ),
    ]
